### ISSUE TITLE
laravel 5.2 Call to a member function connection() on a non-object

### ISSUE THREAD

**Issue by o2-web** [thekordy/auzo#5]
after trying to publish migrations
`php artisan vendor:publish --provider="Kordy\Auzo\AuzoServiceProvider" --tag="migrations"`

i got this error

> PHP Fatal error:  Call to a member function connection() on a non-object in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 3286

**Comment by thekordy** [comment]
I do not know why this is happening to you, try to:
1. Make sure auzo and auzo-tools service providers are included in your `config/app.php`
2. update to auzo 1.1
3. delete old published migration files
4. publish the new auzo migrations
5. do `composer dump -o` 

and see if this solves it.
