### ISSUE TITLE
[compatability with Laravel 5.3] An error occurred while trying to assign a role to a user via the console.

### ISSUE THREAD

**Issue by bigperson** [thekordy/auzo#7]
When you try to assign the role with artisan I get an error
`artisan auzo:user assign 10 Administrator`

> [BadMethodCallException]  
> Call to undefined method Illuminate\Database\Query\Builder::assignRole()  

Laravel 5.3

**Comment by thekordy** [comment]
I am sorry for that error, it should work on Laravel 5.1 and 5.2, I will work on 5.3 compatibility soon.

**Comment by bigperson** [comment]
Thank you. How soon can we expect will work on 5.3?

**Comment by thekordy** [comment]
in a week or two

**Comment by thekordy** [comment]
Solved in last release v1.1.1 .. also make sure you add the `Kordy\Auzo\Traits\HasRoleTrait` to the users model `App\User`
