### ISSUE TITLE
$user->can() always return false

### ISSUE THREAD

**Issue by anhtuan21204** [thekordy/auzo#8]
Hi there,
After set up this repository success, i create some demo data:
- create user
- create ability: 
$ability = AuzoAbility::create([
            'name' => 'ability.name',
            'label' => 'Abiliy Label',
            'tag' => 'ability.tag'
        ]);

- create role:
$role = AuzoRole::create([
    'name' => 'testRole',
    'description' => 'test role description'
]);
- create permission:
       $role->givePermissionTo($ability);
       $user->assignRole($role);
In HomeController: 
        var_dump($user->can('ability.name')); // --> false;

**Comment by thekordy** [comment]
which laravel version?

**Comment by thekordy** [comment]
and would you please try to clone the repo or install the dev-master? seems like latest changes has not been released
